version: "3"
services:
  nginx:
    build:
      context: .
    image: yekta/iamyekta-nginx:latest
    hostname: "nginx"
    domainname: "iamyekta.com"
    ports:
      - "80:80"
    restart: always
    networks:
      - web_network

networks:
  web_network:
    name: web_network